### ISSUE TITLE
link to .io page on project page

### ISSUE THREAD

**Issue by geneorama** [ShirinG/ShirinG.github.io#1]
I suggest that you provide a link to https://shiring.github.io/ShirinG.github.io/ in your https://github.com/ShirinG/ShirinG.github.io/ description. 

Unless the user is familiar with constructing the URL they might land on your project page and not find the actual .io page!

**Comment by geneorama** [comment]
BTW, here's how we did it on the food inspection project: https://github.com/Chicago/food-inspections-evaluation

**Comment by ShirinG** [comment]
Dear Gene,

Thanks, I will definitely check it out!

Thanks also for the suggestion to provide my link! I’ve added it to the readme.

Cheers,
Shirin


------------------------------------------------
Dr. Shirin Glander

Department of Genetic Epidemiology
Institute for Human Genetics
University of Münster, Germany

Albert-Schweitzer-Campus 1, D3
Domagkstraße 3
48149 Münster
T +49(0)251-83-56425
F +49(0)251-83-56205



Von: Gene Leynes [mailto:notifications@github.com]
Gesendet: Monday, April 03, 2017 10:38 PM
An: ShirinG/ShirinG.github.io <ShirinG.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ShirinG/ShirinG.github.io] link to .io page on project page (#1)


BTW, here's how we did it on the food inspection project: https://github.com/Chicago/food-inspections-evaluation

**Comment by geneorama** [comment]
Glad you like the suggestion, I'm closing the issue :+1:
